### ISSUE TITLE
removing obsolete/unnecessary links

### ISSUE THREAD

**Issue by npdoty** [lebaer/pw-index-mockup#1]
I think "Directory" and "Exchange" are both entirely obsolete services, and we should remove the links from the footer.

Also, do we need a copyright notice? I don't actually know what the license for the planWorld source code and design are, but I don't think we need active labeling of copyright in order to use the legal system to get multiple damages in case someone copies a decades-old design.

**Comment by npdoty** [comment]
Personally, I'd love to keep the "What is NOTE?" link, because that page is awesome, both in terms of 90s style and in the cute history of a potentially long-lived project: http://neon.note.amherst.edu/whatis/

**Comment by lebaer** [comment]
Agreed that I don't think we need a copyright notice for legalities, I just like it because it shows how long-lived this whole web project has lasted. Given the move to Google, I'm pretty sure you're right about Directory and Exchange being obsolete, and have removed those as well, and I have no objection to keeping in the What is NOTE link, so I put it back.
